kind = "web"
previewPath = "/"
title = "FOODORO POS"
version = "1.0.0"
id = "artifacts/foodoro"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24753

[services.development]
run = "pnpm --filter @workspace/foodoro run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/foodoro", "run", "build" ]
publicDir = "artifacts/foodoro/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24753"
BASE_PATH = "/"
